# CI/CD Workflow for TWCC's project

name: TWCC CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
      - name: Checkout COMS4156-TWCC Repository
        uses: actions/checkout@v3 # action that checks out repository onto the runner
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests and Jacoco (Code Coverage)
        run: mvn clean test

      - name: Checkstyle and SpotBugs (Static Analysis Bug Finder Tool)
        run: mvn site
      
      - name: Update Reports Directory with Recent Report Generation
        run: cp -r ./target/site ./reports

      - name: Test GitHub Run Variables
        run: |
          echo "Commit from GitHub Actions $github.job-run-${{ github.run_number }}: 
          Add and Commit Recent Report Generation
          Current branch: ${{ github.ref_name }}"

      - name: Add and Commit Recent Report Generation
        uses: EndBug/add-and-commit@v9
        with:
          add: './reports'
          message: |
            "Commit from GitHub Actions ${{ github.job }}-run-${{ github.run_number }}: 
            Add and Commit Recent Report Generation"
          push: origin ${{ github.ref_name }} --set-upstream --force
      
